Novo blog post "Olá 2024"
grupyrn/blog pull request #22
Opened 2024-01-20 20:10 UTC by itepifanio

2024-01-20 22:28 UTC, allythy approved these changes

2024-01-21 18:16 UTC, itepifanio commented
@allythy fiz algumas edições, por favor revisa novamente

2024-01-22 16:08 UTC, allythy commented on _posts/2024-01-20-ola-2024.md
> +geralmente aos sábados de manhã, no SEBRAE. Nossa meta para 2024
SEBRAE-RN

2024-01-22 16:10 UTC, allythy commented on _posts/2024-01-20-ola-2024.md
> +estarão todas documentadas no GitHub do GruPy.
GruPy-RN

2024-01-22 16:12 UTC, allythy commented on _posts/2024-01-20-ola-2024.md
> +Iniciamos a venda de adesivos com a arte GruPy RN, o que vem gerado algum caixa para financiar
Remover o espaço e colocar um traço "GruPy-RN"

2024-01-22 16:12 UTC, allythy commented on _posts/2024-01-20-ola-2024.md
> +Iniciamos a venda de adesivos com a arte GruPy RN, o que vem gerado algum caixa para financiar
Remover o espaço e colocar um traço "GruPy-RN"

2024-01-22 16:17 UTC, allythy requested changes
Alterar o texto da arte

- "Olá 2024" para "Olá, 2024"
- "Um novo ano de GruPy com Python conectando pessoas" para "Um novo ano de GruPy_RN  conectando pessoa"

2024-01-22 16:43 UTC, allythy approved these changes

2024-01-22 16:44 UTC, merged